FROM oven/bun:1.3.11-slim AS base

WORKDIR /app

FROM base AS deps

COPY package.json bun.lock tsconfig.json prisma.config.ts ./

RUN bun install

FROM deps AS build

COPY . .

RUN bunx prisma generate

FROM base AS runtime

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/bun.lock ./bun.lock
COPY --from=build /app/tsconfig.json ./tsconfig.json
COPY --from=build /app/prisma.config.ts ./prisma.config.ts
COPY --from=build /app/src ./src
COPY --from=build /app/prisma ./prisma

EXPOSE 5000

CMD ["bun", "src/scripts/start.ts", "--migrate=deploy"]
